import { randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { app, ipcMain, safeStorage } from 'electron'
import type {
  DesktopEnterpriseContext,
  DesktopHarnessDevice,
  DesktopObisDeviceAuthorization,
  DesktopObisDeviceExchange,
  DesktopObisIdentityConfiguration,
  DesktopObisIdentityStatus,
  DesktopObisMembership,
  DesktopResolvedWorkspace,
  DesktopUserPreference,
  DesktopWorkspaceDefinitionInput,
} from './desktop-obis-identity-shared.ts'

const APP_ORIGIN='dsh-app://app',STORE_VERSION=1,OHP_VERSION='1.0'
interface StoredObisIdentity { version:1;baseURL:string;tenantId:string;deviceId:string;installationId?:string;encryptedAccessToken?:string;encryptedRefreshToken?:string;sessionId?:string;expiresAt?:string;refreshExpiresAt?:string;user?:{ id:string;displayName:string;primaryEmail?:string };membership?:DesktopObisMembership;memberships?:DesktopObisMembership[] }
interface TokenPair { sessionId:string;accessToken:string;refreshToken:string;expiresAt:string;refreshExpiresAt:string }
interface MeResponse { user:{ id:string;displayName:string;primaryEmail?:string };membership:DesktopObisMembership;memberships?:DesktopObisMembership[] }
interface InstallationEnvelope { installation:{ id:string;deviceId:string;status:string };compatibility:unknown }
class ObisHttpError extends Error {constructor(readonly status:number,message:string){super(message)}}
function storePath():string{return join(app.getPath('userData'),'obis-enterprise.json')}function isMissingFile(error:unknown):boolean{return error instanceof Error&&'code'in error&&error.code==='ENOENT'}function requiredMode():boolean{return process.env.OBIS_DESKTOP_REQUIRED?.trim()==='1'}
function validateBaseURL(raw:string):string{const value=raw.trim().replace(/\/$/,''),parsed=new URL(value),localhost=parsed.hostname==='localhost'||parsed.hostname==='127.0.0.1'||parsed.hostname==='::1';if(parsed.protocol!=='https:'&&!(parsed.protocol==='http:'&&localhost))throw new Error('OBIS URL must use HTTPS; HTTP is allowed only for localhost development');parsed.pathname=parsed.pathname.replace(/\/$/,'');parsed.search='';parsed.hash='';return parsed.toString().replace(/\/$/,'')}
function parseStored(value:unknown):StoredObisIdentity|undefined{if(typeof value!=='object'||value===null||Array.isArray(value))return undefined;const row=value as Partial<StoredObisIdentity>;if(row.version!==STORE_VERSION||typeof row.baseURL!=='string'||typeof row.tenantId!=='string'||typeof row.deviceId!=='string')return undefined;return{ version:STORE_VERSION,baseURL:validateBaseURL(row.baseURL),tenantId:row.tenantId.trim(),deviceId:row.deviceId,...(typeof row.installationId==='string'?{ installationId:row.installationId }:{}),...(typeof row.encryptedAccessToken==='string'?{ encryptedAccessToken:row.encryptedAccessToken }:{}),...(typeof row.encryptedRefreshToken==='string'?{ encryptedRefreshToken:row.encryptedRefreshToken }:{}),...(typeof row.sessionId==='string'?{ sessionId:row.sessionId }:{}),...(typeof row.expiresAt==='string'?{ expiresAt:row.expiresAt }:{}),...(typeof row.refreshExpiresAt==='string'?{ refreshExpiresAt:row.refreshExpiresAt }:{}),...(row.user&&typeof row.user.id==='string'&&typeof row.user.displayName==='string'?{ user:row.user }:{}),...(row.membership&&typeof row.membership.tenantId==='string'&&Array.isArray(row.membership.roles)?{ membership:row.membership }:{}),...(Array.isArray(row.memberships)?{ memberships:row.memberships.filter(value=>value&&typeof value.tenantId==='string'&&Array.isArray(value.roles)) }:{}) }}
async function readStored():Promise<StoredObisIdentity|undefined>{try{return parseStored(JSON.parse(await readFile(storePath(),'utf8')) as unknown)}catch(error){if(isMissingFile(error))return undefined;throw error}}
async function writeStored(stored:StoredObisIdentity):Promise<void>{const path=storePath(),temporary=`${path}.tmp`;await mkdir(app.getPath('userData'),{ recursive:true });await writeFile(temporary,`${JSON.stringify(stored,null,2)}\n`,{ mode:0o600 });await rename(temporary,path)}
async function ensureStored():Promise<StoredObisIdentity|undefined>{const existing=await readStored();if(existing)return existing;const baseURL=process.env.OBIS_BASE_URL?.trim(),tenantId=process.env.OBIS_TENANT_ID?.trim();if(!baseURL||!tenantId)return undefined;const stored:StoredObisIdentity={ version:STORE_VERSION,baseURL:validateBaseURL(baseURL),tenantId,deviceId:`desktop_${randomUUID()}` };await writeStored(stored);return stored}
function publicStatus(stored:StoredObisIdentity|undefined):DesktopObisIdentityStatus{return{ configured:stored!==undefined,required:requiredMode(),authenticated:stored?.encryptedRefreshToken!==undefined&&stored.user!==undefined&&stored.membership!==undefined,...(stored?{ baseURL:stored.baseURL,tenantId:stored.tenantId,deviceId:stored.deviceId }:{}),...(stored?.expiresAt?{ expiresAt:stored.expiresAt }:{}),...(stored?.refreshExpiresAt?{ refreshExpiresAt:stored.refreshExpiresAt }:{}),...(stored?.user?{ user:stored.user }:{}),...(stored?.membership?{ membership:stored.membership }:{}),...(stored?.memberships?{ memberships:stored.memberships }:{}) }}
function encrypted(value:string):string{if(!safeStorage.isEncryptionAvailable())throw new Error('macOS secure storage is unavailable; OBIS credentials were not saved');return safeStorage.encryptString(value).toString('base64')}function decrypted(value:string|undefined):string|undefined{if(!value)return undefined;if(!safeStorage.isEncryptionAvailable())throw new Error('macOS secure storage is unavailable; OBIS credentials cannot be read');return safeStorage.decryptString(Buffer.from(value,'base64'))}
function withoutSession(stored:StoredObisIdentity):StoredObisIdentity{return{ version:STORE_VERSION,baseURL:stored.baseURL,tenantId:stored.tenantId,deviceId:stored.deviceId,...(stored.installationId?{ installationId:stored.installationId }:{}) }}
function apiError(payload:unknown,status:number):string{if(payload&&typeof payload==='object'&&!Array.isArray(payload)&&'error'in payload){const error=(payload as{ error?:unknown }).error;if(error&&typeof error==='object'&&!Array.isArray(error)&&'message'in error)return String((error as{ message?:unknown }).message??`OBIS request failed with ${status}`);if(typeof error==='string')return error}return`OBIS request failed with ${status}`}
function isTokenPair(value:unknown):value is TokenPair{if(typeof value!=='object'||value===null||Array.isArray(value))return false;const row=value as Partial<TokenPair>;return typeof row.sessionId==='string'&&typeof row.accessToken==='string'&&typeof row.refreshToken==='string'&&typeof row.expiresAt==='string'&&typeof row.refreshExpiresAt==='string'}
async function requestJson<T>(stored:StoredObisIdentity,path:string,input:{ method?:'GET'|'POST'|'PUT'|'PATCH';body?:unknown;accessToken?:string;allowAccepted?:boolean;ohp?:boolean }={}):Promise<{ status:number;value:T }>{const headers=new Headers({ accept:'application/json' });if(input.body!==undefined)headers.set('content-type','application/json');if(input.accessToken)headers.set('authorization',`Bearer ${input.accessToken}`);if(input.ohp)headers.set('ohp-version',OHP_VERSION);const response=await fetch(`${stored.baseURL}${path}`,{ method:input.method??'GET',headers,...(input.body!==undefined?{ body:JSON.stringify(input.body) }:{}) }),payload=await response.json().catch(()=>undefined) as T;if(!response.ok&&!(input.allowAccepted&&response.status===202))throw new ObisHttpError(response.status,apiError(payload,response.status));return{ status:response.status,value:payload }}
function channel():'canary'|'stable'|'enterprise-lts'{const value=process.env.OBIS_HARNESS_CHANNEL?.trim();return value==='canary'||value==='enterprise-lts'?value:'stable'}
function installationBody(stored:StoredObisIdentity){return{ deviceId:stored.deviceId,deviceName:`${process.platform}-${process.arch}`,os:process.platform,architecture:process.arch,harnessVersion:app.getVersion(),bridgeVersion:OHP_VERSION,protocolVersions:[OHP_VERSION],capabilities:['agent','tools','skills','session','desktop-shell','tenant-switch','device-control'],channel:channel() }}
async function ensureInstallation(stored:StoredObisIdentity,accessToken:string):Promise<StoredObisIdentity>{if(stored.installationId){try{const heartbeat=await requestJson<InstallationEnvelope>(stored,`/v1/harness/installations/${encodeURIComponent(stored.installationId)}/heartbeat`,{ method:'POST',body:{ harnessVersion:app.getVersion(),bridgeVersion:OHP_VERSION,protocolVersions:[OHP_VERSION],capabilities:installationBody(stored).capabilities },accessToken,ohp:true });if(heartbeat.value.installation?.status!=='revoked')return stored}catch(error){if(!(error instanceof ObisHttpError&&error.status===404))throw error}}const registered=await requestJson<InstallationEnvelope>(stored,'/v1/harness/installations',{ method:'POST',body:installationBody(stored),accessToken,ohp:true }),installationId=registered.value.installation?.id;if(typeof installationId!=='string')throw new Error('OBIS Harness registration returned an invalid installation');const next={ ...stored,installationId };await writeStored(next);return next}
async function attachIdentity(stored:StoredObisIdentity,tokens:TokenPair):Promise<StoredObisIdentity>{const me=await requestJson<MeResponse>(stored,'/v1/me',{ accessToken:tokens.accessToken }),base:StoredObisIdentity={ ...withoutSession(stored),encryptedAccessToken:encrypted(tokens.accessToken),encryptedRefreshToken:encrypted(tokens.refreshToken),sessionId:tokens.sessionId,expiresAt:tokens.expiresAt,refreshExpiresAt:tokens.refreshExpiresAt,user:me.value.user,membership:me.value.membership,...(me.value.memberships?{ memberships:me.value.memberships }:{}) };const next=await ensureInstallation(base,tokens.accessToken);await writeStored(next);return next}
async function refreshStored(stored:StoredObisIdentity):Promise<StoredObisIdentity>{const refreshToken=decrypted(stored.encryptedRefreshToken);if(!refreshToken)return stored;try{const refreshed=await requestJson<TokenPair>(stored,'/v1/auth/refresh',{ method:'POST',body:{ refreshToken } });if(!isTokenPair(refreshed.value))throw new Error('OBIS refresh returned an invalid token envelope');return attachIdentity(stored,refreshed.value)}catch(error){if(error instanceof ObisHttpError&&(error.status===401||error.status===403))await writeStored(withoutSession(stored));throw error}}
async function authenticatedStored():Promise<{ stored:StoredObisIdentity;accessToken:string }>{let stored=await ensureStored();if(!stored)throw new Error('Configure OBIS before using enterprise controls');let accessToken=decrypted(stored.encryptedAccessToken);if(!accessToken||stored.expiresAt&&Date.parse(stored.expiresAt)<=Date.now()+30_000){stored=await refreshStored(stored);accessToken=decrypted(stored.encryptedAccessToken)}if(!accessToken)throw new Error('Sign in to OBIS before using enterprise controls');return{ stored,accessToken }}
async function currentIdentity():Promise<DesktopObisIdentityStatus>{const stored=await ensureStored();if(!stored)return publicStatus(undefined);if(!stored.encryptedRefreshToken)return publicStatus(stored);const accessToken=decrypted(stored.encryptedAccessToken);if(accessToken&&(!stored.expiresAt||Date.parse(stored.expiresAt)>Date.now()+30_000)){try{const me=await requestJson<MeResponse>(stored,'/v1/me',{ accessToken }),next=await ensureInstallation({ ...stored,user:me.value.user,membership:me.value.membership,...(me.value.memberships?{ memberships:me.value.memberships }:{}) },accessToken);await writeStored(next);return publicStatus(next)}catch{/* rotate below */}}try{return publicStatus(await refreshStored(stored))}catch(error){if(error instanceof ObisHttpError&&(error.status===401||error.status===403))return publicStatus(await readStored());throw error}}
function trustedSender(event:Electron.IpcMainInvokeEvent):boolean{return event.senderFrame?.url.startsWith(`${APP_ORIGIN}/`)===true}function requireTrusted(event:Electron.IpcMainInvokeEvent):void{if(!trustedSender(event))throw new Error('enterprise identity IPC rejected an untrusted sender')}

function installIdentityIpc():void{
  ipcMain.handle('dsh:obis-identity-status',async (event)=>{requireTrusted(event);return currentIdentity()})
  ipcMain.handle('dsh:obis-identity-configure',async(event,value:unknown)=>{requireTrusted(event);if(typeof value!=='object'||value===null||Array.isArray(value))throw new Error('OBIS identity configuration must be an object');const row=value as Partial<DesktopObisIdentityConfiguration>;if(typeof row.baseURL!=='string'||typeof row.tenantId!=='string'||row.tenantId.trim()==='')throw new Error('OBIS URL and tenant are required');const existing=await readStored(),baseURL=validateBaseURL(row.baseURL),tenantId=row.tenantId.trim(),sameAuthority=existing?.baseURL===baseURL&&existing.tenantId===tenantId,next:StoredObisIdentity=sameAuthority&&existing?existing:{ version:STORE_VERSION,baseURL,tenantId,deviceId:existing?.deviceId??`desktop_${randomUUID()}` };await writeStored(next);return publicStatus(next)})
  ipcMain.handle('dsh:obis-identity-device-start',async (event)=>{requireTrusted(event);const stored=await ensureStored();if(!stored)throw new Error('Configure the OBIS URL and tenant before signing in');return(await requestJson<DesktopObisDeviceAuthorization>(stored,'/v1/auth/github/device/start',{ method:'POST' })).value})
  ipcMain.handle('dsh:obis-identity-device-exchange',async(event,deviceCode:unknown):Promise<DesktopObisDeviceExchange>=>{requireTrusted(event);if(typeof deviceCode!=='string'||deviceCode.trim()==='')throw new Error('GitHub device code is required');const stored=await ensureStored();if(!stored)throw new Error('Configure the OBIS URL and tenant before signing in');const response=await requestJson<TokenPair|{ status:'authorization_pending'|'slow_down';retryAfterSeconds?:number }>(stored,'/v1/auth/github/device/exchange',{ method:'POST',body:{ tenantId:stored.tenantId,deviceCode:deviceCode.trim(),deviceId:stored.deviceId },allowAccepted:true });if(response.status===202)return response.value as DesktopObisDeviceExchange;if(!isTokenPair(response.value))throw new Error('OBIS device exchange returned an invalid token envelope');return{ status:'authenticated',identity:publicStatus(await attachIdentity(stored,response.value)) }})
  ipcMain.handle('dsh:obis-identity-refresh',async (event)=>{requireTrusted(event);return currentIdentity()})
  ipcMain.handle('dsh:obis-context',async (event)=>{requireTrusted(event);const{ stored,accessToken }=await authenticatedStored();return(await requestJson<DesktopEnterpriseContext>(stored,'/v1/desktop/context',{ accessToken })).value})
  ipcMain.handle('dsh:obis-switch-tenant',async(event,target:unknown)=>{requireTrusted(event);if(typeof target!=='string'||!target.trim())throw new Error('Target tenant is required');const{ stored,accessToken }=await authenticatedStored();if(target.trim()===stored.tenantId)return publicStatus(stored);const response=await requestJson<TokenPair>(stored,'/v1/auth/switch-tenant',{ method:'POST',body:{ targetTenantId:target.trim() },accessToken });if(!isTokenPair(response.value))throw new Error('OBIS tenant switch returned an invalid token envelope');const nextAuthority:StoredObisIdentity={ ...withoutSession(stored),tenantId:target.trim() };delete nextAuthority.installationId;return publicStatus(await attachIdentity(nextAuthority,response.value))})
  ipcMain.handle('dsh:obis-workspace',async (event)=>{requireTrusted(event);const{ stored,accessToken }=await authenticatedStored();return(await requestJson<DesktopResolvedWorkspace>(stored,'/v1/desktop/workspace',{ accessToken })).value})
  ipcMain.handle('dsh:obis-workspace-preferences',async(event,value:unknown)=>{requireTrusted(event);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Desktop preferences must be an object');const{ stored,accessToken }=await authenticatedStored();return(await requestJson<DesktopUserPreference>(stored,'/v1/desktop/preferences',{ method:'PUT',body:value,accessToken })).value})
  ipcMain.handle('dsh:obis-devices',async (event)=>{requireTrusted(event);const{ stored,accessToken }=await authenticatedStored();return(await requestJson<{ items:DesktopHarnessDevice[] }>(stored,'/v1/desktop/devices',{ accessToken })).value.items})
  ipcMain.handle('dsh:obis-device-revoke',async(event,installationId:unknown)=>{requireTrusted(event);if(typeof installationId!=='string'||!installationId.trim())throw new Error('Installation id is required');const{ stored,accessToken }=await authenticatedStored(),devices=(await requestJson<{ items:DesktopHarnessDevice[] }>(stored,'/v1/desktop/devices',{ accessToken })).value.items,target=devices.find(item=>item.id===installationId);await requestJson(stored,`/v1/desktop/devices/${encodeURIComponent(installationId)}/revoke`,{ method:'POST',accessToken });if(target?.deviceId===stored.deviceId)await writeStored(withoutSession(stored))})
  ipcMain.handle('dsh:obis-workspace-definitions',async (event)=>{requireTrusted(event);const{ stored,accessToken }=await authenticatedStored();return(await requestJson<{ items:unknown[] }>(stored,'/v1/management/desktop/workspaces',{ accessToken })).value.items})
  ipcMain.handle('dsh:obis-workspace-definition-save',async(event,id:unknown,value:unknown)=>{requireTrusted(event);if(typeof id!=='string'||!id.trim()||!value||typeof value!=='object'||Array.isArray(value))throw new Error('Workspace id and definition are required');const{ stored,accessToken }=await authenticatedStored();return(await requestJson<unknown>(stored,`/v1/management/desktop/workspaces/${encodeURIComponent(id)}`,{ method:'PUT',body:value,accessToken })).value})
  ipcMain.handle('dsh:obis-identity-logout',async (event)=>{requireTrusted(event);const stored=await ensureStored();if(!stored)return publicStatus(undefined);let accessToken=decrypted(stored.encryptedAccessToken);if((!accessToken||stored.expiresAt&&Date.parse(stored.expiresAt)<=Date.now())&&stored.encryptedRefreshToken){try{const refreshed=await refreshStored(stored);accessToken=decrypted(refreshed.encryptedAccessToken)}catch{accessToken=undefined}}if(accessToken){try{await requestJson(stored,'/v1/auth/logout',{ method:'POST',accessToken })}catch{/* local credentials are destroyed even if OBIS is offline */}}const cleared=withoutSession(stored);await writeStored(cleared);return publicStatus(cleared)})
}
void app.whenReady().then(()=>{installIdentityIpc()})
